name: dbt CI

on:
  push:
    branches: [ main ]

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          
          echo '${{ secrets.DBT_USER_CREDS }}' > ~/keyfile.json
          
          cat <<EOF > ~/.dbt/profiles.yml
          homestaging_analytics:
            target: prod
            outputs:
              prod:
                dataset: StagingOrders
                job_execution_timeout_seconds: 300
                job_retries: 1
                location: US-WEST1
                type: bigquery
                method: service-account
                project: data-438623
                threads: 1
                keyfile: ~/keyfile.json
                location: US
          EOF

      - name: Run dbt
        run: |
          dbt deps
          dbt run
          dbt test
